apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
spec:
  selector:
    app: tsk3  
  ports:
  - name: http
    port: 80              # Порт Service
    targetPort: 80        # Порт контейнера nginx
  - name: multitool
    port: 1180            # Порт Service для multitool
    targetPort: 1180      # Порт контейнера multitool
  type: ClusterIP         # Тип Service для внутреннего доступа в кластере
