services:
  debian:
    image: debian:11
    container_name: debian_host
    command: sleep infinity
    privileged: true

  centos:
    image: centos:7
    container_name: centos_host
    command: sleep infinity
    privileged: true

  ubuntu:
    image: ubuntu:20.04
    container_name: ubuntu_host
    command: sleep infinity
    privileged: true
