resource "local_file" "ansible_inventory" {
  content = <<-EOT
    # Ansible inventory generated by Terraform
    ---
    clickhouse:
      hosts:
        ${yandex_compute_instance.vms["clickhouse-01"].name}:
          ansible_host: ${yandex_compute_instance.vms["clickhouse-01"].network_interface[0].nat_ip_address}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/shvirtd19_pvk
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    vector:
      hosts:
        ${yandex_compute_instance.vms["vector-01"].name}:
          ansible_host: ${yandex_compute_instance.vms["vector-01"].network_interface[0].nat_ip_address}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/shvirtd19_pvk
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    lighthouse:
      hosts:
        ${yandex_compute_instance.vms["lighthouse-01"].name}:
          ansible_host: ${yandex_compute_instance.vms["lighthouse-01"].network_interface[0].nat_ip_address}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/shvirtd19_pvk
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  EOT

  filename = "${path.module}/prod_tf.yml"
}

output "inventory_file" {
  value = local_file.ansible_inventory.filename
  description = "Path to generated Ansible inventory file"
}

resource "null_resource" "save_outputs" {
  triggers = {
    outputs = local_file.ansible_inventory.content
  }

  provisioner "local-exec" {
    command = "echo '${local_file.ansible_inventory.content}' >../inventory/prod.yml"
  }
}
